### ISSUE TITLE
does not start

### ISSUE THREAD

**Issue by LCPallares** [billyeatcookies/biscuit#173] opened 2023-11-13 20:37 UTC
## Bug
> crashes, shows the cookie screen and closes leaving this error
D:\P\Programacion\Python\IDLE\biscuit\dist>biscuit
Traceback (most recent call last):
  File "biscuit\__main__.py", line 17, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "biscuit\__init__.py", line 11, in <module>
ModuleNotFoundError: No module named 'biscuit.core'
[2208] Failed to execute script '__main__' due to unhandled exception!

D:\P\Programacion\Python\IDLE\biscuit\dist>

### System Information
-  PyInstaller: 4.10
- Python: 3.6.5
- Platform: Windows-7-6.1.7601-SP1
- wrote D:\P\Programacion\Python\IDLE\biscuit\biscuit.spec
- UPX is not available.

**Comment by billyeatcookies** [comment] 2023-11-15 05:31
Hey @LCPallares thanks for opening an issue on this!
As of now I'm unable to reproduce this issue, hence the late response. I will diagnose the issue asap, will be updating this issue on the changes made regarding this problem.

**Comment by billyeatcookies** [comment] 2023-11-15 20:02
@LCPallares issue has been fixed in latest release: https://github.com/billyeatcookies/biscuit/releases/tag/v2.33.0

Please test this and let me know if the bug still persists, thanks for opening the issue ❤️ 

![image](https://github.com/billyeatcookies/biscuit/assets/70792552/0fc04863-8149-44cc-9d45-d67ce99a1c1f)

**Closed by billyeatcookies** 2023-11-15 20:02 UTC
Labels: bug
